limit:
  KNOCKBACK: 35
blacklist:
  items:
    - "DIAMOND_HOE"


# Below are listed the ONLY allowed enchantment types (names). They must be cAse-SeNsItIvE!
#
# --------------------------------------------------------
#
#   ARROW_DAMAGE, ARROW_FIRE, ARROW_INFINITE, ARROW_KNOCKBACK
#   BINDING_CURSE, CHANNELING, DAMAGE_ALL, DAMAGE_ARTHROPODS
#   DAMAGE_UNDEAD, DEPTH_STRIDER, DIG_SPEED, DURABILITY
#   FIRE_ASPECT, FROST_WALKER, IMPALING, KNOCKBACK
#   LOOT_BONUS_BLOCKS, LOOT_BONUS_MOBS, LOYALTY
#   LUCK, LURE, MENDING, MULTISHOT
#   OXYGEN, PIERCING, PROTECTION_ENVIRONMENTAL, PROTECTION_EXPLOSIONS
#   PROTECTION_FALL, PROTECTION_FIRE, PROTECTION_PROJECTILE, QUICK_CHARGE
#   RIPTIDE, SILK_TOUCH, SOUL_SPEED, SWEEPING_EDGE
#   THORNS, VANISHING_CURSE, WATER_WORKER
#
# --------------------------------------------------------
#
# Made by: wxip#3544